version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    container_name: ama-frontend
    networks:
      - ama-frontend-net
    volumes:
      - ./frontend/src:/usr/app/src
      - ./frontend/public:/usr/app/public
    depends_on:
      - backend
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    container_name: ama-backend
    networks:
      - ama-backend-net
      - ama-frontend-net
    volumes:
      - ./backend/src:/usr/app/src
      - ./backend/package.json:/usr/app/package.json
    links:
      - "db:database"
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - ${MONGODB_LOCAL_PORT}:${MONGODB_DOCKER_PORT}
    container_name: ama-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
    networks:
      - ama-backend-net
    volumes:
      - mongo-data:/data/db

networks:
  ama-frontend-net:
  ama-backend-net:

volumes:
  mongo-data:
    driver: local
